SET_RESOURCE_LIMIT_QUERY = "ALTER SYSTEM SET RESOURCE_LIMIT = TRUE"
SET_SESSION_CONTAINER_QUERY = "ALTER SESSION SET CONTAINER = FREEPDB1"
CREATE_ROLE_MANAGER_QUERY = "CREATE ROLE R_MANAGER"
CREATE_ROLE_EMPLOYEE_QUERY = "CREATE ROLE R_EMPLOYEE"

CREATE_PROFILE_MANAGER_QUERY = """
    CREATE PROFILE PF_MANAGER LIMIT 
        SESSIONS_PER_USER {session_per_user} 
        CPU_PER_SESSION 1000 
        CPU_PER_CALL 1000 
        CONNECT_TIME {connect_time} 
        IDLE_TIME {idle_time}
        LOGICAL_READS_PER_SESSION 1000 
        LOGICAL_READS_PER_CALL 1000 
        PRIVATE_SGA 20K 
        COMPOSITE_LIMIT 1000 
        PASSWORD_LIFE_TIME 180 
        PASSWORD_REUSE_TIME 180 
        PASSWORD_REUSE_MAX 5 
        PASSWORD_LOCK_TIME 1 
        PASSWORD_GRACE_TIME 7 
        FAILED_LOGIN_ATTEMPTS 3 
        PASSWORD_VERIFY_FUNCTION NULL
    """
CREATE_PROFILE_EMPLOYEE_QUERY = """
    CREATE PROFILE PF_EMPLOYEE LIMIT
        SESSIONS_PER_USER {session_per_user} 
        CPU_PER_SESSION 1000 
        CPU_PER_CALL 1000 
        CONNECT_TIME {connect_time} 
        IDLE_TIME {idle_time} 
        LOGICAL_READS_PER_SESSION 1000 
        LOGICAL_READS_PER_CALL 1000 
        PRIVATE_SGA 20K 
        COMPOSITE_LIMIT 1000 
        PASSWORD_LIFE_TIME 180 
        PASSWORD_REUSE_TIME 180 
        PASSWORD_REUSE_MAX 5 
        PASSWORD_LOCK_TIME 1 
        PASSWORD_GRACE_TIME 7 
        FAILED_LOGIN_ATTEMPTS 3 
        PASSWORD_VERIFY_FUNCTION NULL
    """

CREATE_TABLESPACE_QUERY = """
    CREATE TABLESPACE {tablespace_name}
    DATAFILE '{tablespace_name}.DBF'
    SIZE 10M
    AUTOEXTEND ON
    NEXT 10M
    MAXSIZE 100M
    EXTENT MANAGEMENT LOCAL
    SEGMENT SPACE MANAGEMENT AUTO
"""
DROP_TABLESPACE_EMPLOYEE_QUERY = """DROP TABLESPACE TBS_EMPLOYEE DROP QUOTA INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS"""
DROP_PROFILE_EMPLOYEE_QUERY = """DROP PROFILE PF_EMPLOYEE CASCADE"""
DROP_ROLE_EMPLOYEE_QUERY = """DROP ROLE R_EMPLOYEE"""
DROP_TABLESPACE_MANAGER_QUERY = """DROP TABLESPACE TBS_MANAGER DROP QUOTA INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS"""
DROP_PROFILE_MANAGER_QUERY = """DROP PROFILE PF_MANAGER CASCADE"""
DROP_ROLE_MANAGER_QUERY = """DROP ROLE R_MANAGER"""

SELECT_USER_ROLE_QUERY = "SELECT GRANTED_ROLE FROM USER_ROLE_PRIVS"
SELECT_USER_TABLESPACE_QUERY = "SELECT TABLESPACE_NAME FROM USER_TABLESPACES"
# ANY TABLESPACE START WITH TBS
SELECT_DBA_TABLESPACES_QUERY = "SELECT TABLESPACE_NAME FROM DBA_TABLESPACES WHERE REGEXP_LIKE (TABLESPACE_NAME, '^TBS.*$')"
SELECT_DBA_PROFILES_QUERY = "SELECT DISTINCT PROFILE FROM DBA_PROFILES WHERE REGEXP_LIKE (PROFILE, '^PF_.*$')"
SELECT_DBA_ROLES_QUERY = "SELECT DISTINCT ROLE FROM DBA_ROLES WHERE REGEXP_LIKE (ROLE, '^R_.*$')"